/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author HYPE AMD
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import database.Koneksi;
import java.sql.SQLException;
import controller.MahasiswaController;
import model.Mahasiswa;

public class FormMahasiswa extends javax.swing.JPanel {
    
    
    MahasiswaController controller = new MahasiswaController();
    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
    initComponents();
    tampilData(); // Panggil fungsi tampil data saat form pertama kali dimuat
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        cmbSemester = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cmbProdi = new javax.swing.JComboBox<>();
        cmbKelas = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        jLabel4.setText("Semester");

        jLabel6.setText("Status");

        txtNim.addActionListener(this::txtNimActionPerformed);

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", " " }));
        cmbSemester.addActionListener(this::cmbSemesterActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Alumni", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNim)
                    .addComponent(txtNama)
                    .addComponent(cmbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStatus, 0, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Kelas");

        jLabel8.setText("Prodi");

        jLabel9.setText("Email");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Teknologi Sipil" }));

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "1B", "2A", "2B", "3A", "3B", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProdi, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnUbah.setBackground(new java.awt.Color(204, 204, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnSimpan.setBackground(new java.awt.Color(0, 102, 153));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnCari.setBackground(new java.awt.Color(0, 102, 153));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("CARI");
        btnCari.addActionListener(this::btnCariActionPerformed);

        txtCari.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtCari.setText("Cari NIM / Nama");
        txtCari.addActionListener(this::txtCariActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addGap(0, 506, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NIM", "Nama", "Semester", "Status", "Prodi", "Kelas", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMahasiswa);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
// 1. Ambil teks keyword yang diketik di kolom cari
String keyword = txtCari.getText().trim();

// 2. Jika kolom cari kosong, langsung reset tabel nampilin semua data
if (    !keyword.equals("")) {
} else {
    tampilData();
    return;
        }

// 3. Buat model tabel baru untuk menampung hasil pencarian
DefaultTableModel model = new DefaultTableModel();
model.addColumn("No");
model.addColumn("NIM");
model.addColumn("Nama");
model.addColumn("Semester");
model.addColumn("Status");
model.addColumn("Prodi");
model.addColumn("Kelas");
model.addColumn("Email");

// 4. Query SQL dengan operator LIKE untuk mencari data berdasarkan NIM atau Nama
String sql = "SELECT * FROM mahasiswa WHERE nim LIKE ? OR nama LIKE ?";

try {
    int no = 1;
    Connection conn = database.Koneksi.getKoneksi();
    PreparedStatement ps = conn.prepareStatement(sql);
    
    // Set parameter keyword dengan wildcard % (pencarian fleksibel)
    ps.setString(1, "%" + keyword + "%");
    ps.setString(2, "%" + keyword + "%");
    
    ResultSet rs = ps.executeQuery();
    
    // Looping masukkan hasil cari ke tabel
    while(rs.next()) {
        model.addRow(new Object[]{
            no++,
            rs.getString("nim"),
            rs.getString("nama"),
            rs.getInt("semester"),
            rs.getString("status"),
            rs.getString("prodi"),
            rs.getString("kelas"),
            rs.getString("email")
        });
    }
    
    // Set hasil pencarian ke JTable
    tblMahasiswa.setModel(model);
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Mencari Data: " + e.getMessage());
}
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    // 1. Ambil teks/pilihan dari komponen GUI
String nim = txtNim.getText().trim();
String nama = txtNama.getText().trim();
String semester = cmbSemester.getSelectedItem().toString();
String status = cmbStatus.getSelectedItem().toString();
String prodi = cmbProdi.getSelectedItem().toString();
String kelas = cmbKelas.getSelectedItem().toString();
String email = txtEmail.getText().trim();

// 2. Validasi standar agar NIM dan Nama tidak boleh kosong
if (nim.equals("") || nama.equals("")) {
    JOptionPane.showMessageDialog(this, "NIM dan Nama tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// 3. Siapkan query SQL untuk insert data
String sql = "INSERT INTO mahasiswa (nim, nama, semester, status, prodi, kelas, email) VALUES (?, ?, ?, ?, ?, ?, ?)";

try {
    Connection conn = database.Koneksi.getKoneksi();
    PreparedStatement ps = conn.prepareStatement(sql);
    
    // Pasangkan data sesuai urutan tanda tanya (?) di query
    ps.setString(1, nim);
    ps.setString(2, nama);
    ps.setInt(3, Integer.parseInt(semester));
    ps.setString(4, status);
    ps.setString(5, prodi);
    ps.setString(6, kelas);
    ps.setString(7, email);

    // Eksekusi simpan ke MySQL
    ps.executeUpdate();
    JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Disimpan!");
    
    // 4. Panggil lagi method tampilData() biar tabel langsung nge-refresh otomatis
    tampilData();
    
    // 5. Bersihkan kembali kotak inputan di form
    txtNim.setText("");
    txtNama.setText("");
    txtEmail.setText("");
    cmbSemester.setSelectedIndex(0);
    cmbStatus.setSelectedIndex(0);
    cmbProdi.setSelectedIndex(0);
    cmbKelas.setSelectedIndex(0);
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data: " + e.getMessage());
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
    // 1. Kosongkan semua textfield
txtNim.setText("");
txtNama.setText("");
txtEmail.setText("");

// 2. Reset semua combobox ke pilihan paling atas (index 0)
cmbSemester.setSelectedIndex(0);
cmbStatus.setSelectedIndex(0);
cmbProdi.setSelectedIndex(0);
cmbKelas.setSelectedIndex(0);

// 3. Buka kembali kunci JTextField NIM biar bisa diketik
txtNim.setEditable(true);

// 4. Refresh tabel biar balik nampilin semua data (jika sebelumnya habis nyari data)
tampilData(); // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSemesterActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
    // 1. Ambil baris ke berapa yang sedang diklik oleh user
    int baris = tblMahasiswa.rowAtPoint(evt.getPoint());
    
    // 2. Ambil data dari kolom tabel berdasarkan baris yang diklik
    String nim = tblMahasiswa.getValueAt(baris, 1).toString();
    String nama = tblMahasiswa.getValueAt(baris, 2).toString();
    String semester = tblMahasiswa.getValueAt(baris, 3).toString();
    String status = tblMahasiswa.getValueAt(baris, 4).toString();
    String prodi = tblMahasiswa.getValueAt(baris, 5).toString();
    String kelas = tblMahasiswa.getValueAt(baris, 6).toString();
    String email = tblMahasiswa.getValueAt(baris, 7).toString();
    
    // 3. Set data tersebut agar muncul kembali ke komponen inputan di atas
    txtNim.setText(nim);
    txtNama.setText(nama);
    cmbSemester.setSelectedItem(semester);
    cmbStatus.setSelectedItem(status);
    cmbProdi.setSelectedItem(prodi);
    cmbKelas.setSelectedItem(kelas);
    txtEmail.setText(email);
    
    // 4. Kunci JTextField NIM agar tidak bisa diedit (karena NIM adalah Primary Key)
    txtNim.setEditable(false);    // TODO add your handling code here:
    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    // 1. Ambil data dari komponen GUI
String nim = txtNim.getText().trim();
String nama = txtNama.getText().trim();
String semester = cmbSemester.getSelectedItem().toString();
String status = cmbStatus.getSelectedItem().toString();
String prodi = cmbProdi.getSelectedItem().toString();
String kelas = cmbKelas.getSelectedItem().toString();
String email = txtEmail.getText().trim();

// 2. Validasi inputan tidak boleh kosong
if (nim.equals("") || nama.equals("")) {
    JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu yang ingin diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// 3. Query SQL untuk mengupdate data berdasarkan NIM
String sql = "UPDATE mahasiswa SET nama=?, semester=?, status=?, prodi=?, kelas=?, email=? WHERE nim=?";

try {
    Connection conn = database.Koneksi.getKoneksi();
    PreparedStatement ps = conn.prepareStatement(sql);
    
    // Pasangkan data sesuai urutan tanda tanya (?) di query UPDATE
    ps.setString(1, nama);
    ps.setInt(2, Integer.parseInt(semester));
    ps.setString(3, status);
    ps.setString(4, prodi);
    ps.setString(5, kelas);
    ps.setString(6, email);
    ps.setString(7, nim); // WHERE nim=?

    // Eksekusi update ke MySQL
    ps.executeUpdate();
    JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Diubah!");
    
    // 4. Refresh tabel agar data terbaru langsung muncul
    tampilData();
    
    // 5. Bersihkan kembali form inputan dan buka kunci NIM
    txtNim.setText("");
    txtNama.setText("");
    txtEmail.setText("");
    cmbSemester.setSelectedIndex(0);
    cmbStatus.setSelectedIndex(0);
    cmbProdi.setSelectedIndex(0);
    cmbKelas.setSelectedIndex(0);
    txtNim.setEditable(true); // Biar NIM bisa diketik lagi buat input baru
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Mengubah Data: " + e.getMessage());
}    // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    // 1. Ambil NIM dari textfield
String nim = txtNim.getText().trim();

// 2. Validasi apakah user sudah memilih data yang mau dihapus
if (nim.equals("")) {
    JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// 3. Munculkan pop-up konfirmasi biar gak sengaja kehapus
int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data dengan NIM " + nim + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

// Jika user memilih YES (tombol yakin diklik)
if (konfirmasi == JOptionPane.YES_OPTION) {
    // Query SQL untuk menghapus data berdasarkan NIM
    String sql = "DELETE FROM mahasiswa WHERE nim=?";
    
    try {
        Connection conn = database.Koneksi.getKoneksi();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nim);
        
        // Eksekusi hapus di MySQL
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Dihapus!");
        
        // 4. Refresh tabel
        tampilData();
        
        // 5. Bersihkan kembali form inputan dan buka kunci NIM
        txtNim.setText("");
        txtNama.setText("");
        txtEmail.setText("");
        cmbSemester.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        cmbProdi.setSelectedIndex(0);
        cmbKelas.setSelectedIndex(0);
        txtNim.setEditable(true);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Menghapus Data: " + e.getMessage());
    }
}    // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables

    private void tampilData() {
    // 1. Siapkan model tabel kosong beserta judul kolomnya
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("NIM");
    model.addColumn("Nama");
    model.addColumn("Semester");
    model.addColumn("Status");
    model.addColumn("Prodi");
    model.addColumn("Kelas");
    model.addColumn("Email");
    
    try {
        int no = 1;
        // 2. Query buat ambil semua data dari tabel mahasiswa
        String sql = "SELECT * FROM mahasiswa";
        Connection conn = database.Koneksi.getKoneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        // 3. Looping untuk memasukkan baris demi baris data dari DB ke model tabel
        while(rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getInt("semester"),
                rs.getString("status"),
                rs.getString("prodi"),
                rs.getString("kelas"),
                rs.getString("email")
            });
        }
        // 4. Set model yang udah terisi data tadi ke JTable kamu
        tblMahasiswa.setModel(model);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

}